name: aks infra pipeline
on:
  workflow_dispatch:
permissions:
 id_token: write
 content: read
jobs:
  test-azure:
   runs-on: self-hosted
   steps: 
    name: checkout
    uses: actions/checkout@v4
    name: azure login
    uses: 
